nodes:

- node: aem-author
  roles:
  - role: wcm-io-samples-cms
    variant: aem-author
  config:
    replication.author.publishTargets:
    - name: publish1
      url: http://localhost:4503
      transportUser: admin
      # Has to be encrypted with the correct key, see http://www.wemblog.com/2012/03/how-to-use-crypto-support-in-cq55.html
      transportPassword: "{898e59830fb757c65409ad02f97a7c56a1eb235fbd7712434afbf9c0b224515d9fbfd16f35d3d3b81ecca341630c0b9a}"

- node: aem-publish
  roles:
  - role: wcm-io-samples-cms
    variant: aem-publish
  config:
    replication.publish.flushTarget:
      name: dispatcher1
      url: https://www.wcmio-sample.de

- node: webserver
  roles:
  - role: aem-dispatcher
    variants:
    - aem-author
    - ssl
    config:
      httpd.serverName: cms.wcmio-sample.de
      httpd.accessRestriction.adminAccessFromIp: 80.150.190.128/26 87.193.246.218
      dispatcher:
        cache:
          rootPath: /var/cache/author1
        renderInstance:
          host: localhost
          port: 4502
  - role: aem-dispatcher
    variants:
    - aem-publish
    - ssl
    config:
      httpd.accessRestriction.adminAccessFromIp: 80.150.190.128/26
      dispatcher:
        cache:
          rootPath: /var/cache/publish1
          statFilesLevel: 3
        renderInstance:
          host: localhost
          port: 4503

config:
  contentPackage.group: "wcm-io-samples"
  jvm:
    path: /usr/lib/jvm/jdk-8-oracle-x64
    heapspace:
      min: 3072m
      max: 3072m
    timezone: Europe/Berlin
  httpd:
    accessRestriction:
      dispatcherFlushFromHost: localhost
      dispatcherFlushFromIp: 127.0.0.1
    ssl:
      enforce: true
      certificateFile: /etc/ssl/certs/wcmio-sample.de.crt
      certificateKeyFile: /etc/ssl/private/wcmio-sample.de.key
      caCertificatePath: /etc/ssl/certs
      caCertificateFile: /etc/ssl/certs/GeoTrust_SSL_CA_G2_Cert_bundle.pem
  app.sampleContent: false

  # Force-Override site URLs in all site configs on the system
  configOverrides:
    "/content/wcm-io-samples":
    - io.wcm.handler.url.SiteConfig/siteUrl="https://www.wcmio-sample.de"
    - io.wcm.handler.url.SiteConfig/siteUrlSecure="https://www.wcmio-sample.de"
    - io.wcm.handler.url.SiteConfig/siteUrlAuthor="https://cms.wcmio-sample.de"


tenants:

- tenant: www.wcmio-sample.de
  config:
    httpd:
      serverAliasNames:
      - wcmio-sample.de
      rootRedirect.url: /en.html
    sling.mapping.rootPath: /content/wcm-io-samples
