# Project-specific AEM configuration

# Inherit default AEM functionality from "AEM Definitions", see http://devops.wcm.io/conga/definitions/aem/
inherits:
- role: aem-cms

variants:
- variant: aem-author
- variant: aem-publish

templateDir: wcm-io-samples-aem-cms

files:

# AEM OSGi System Configuration
- file: wcm-io-samples-aem-cms-config.provisioning
  dir: packages
  template: wcm-io-samples-aem-cms-config.provisioning.hbs
  postProcessors:
  - aem-contentpackage-osgiconfig
  postProcessorOptions:
    contentPackage:
      name: wcm-io-samples-aem-cms-config
      rootPath: /apps/wcm-io-samples-aem-cms-config/config
      filters:
      - filter: /apps/wcm-io-samples-aem-cms-config

# AEM Systems users with ACLs (Author)
- file: wcm-io-samples-aem-cms-author-systemusers.json
  dir: packages
  template: wcm-io-samples-aem-cms-author-systemusers.json.hbs
  variants:
  - aem-author
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: wcm-io-samples-aem-cms-author-systemusers
      acHandling: merge
      rootPath: /
      filters:
      - filter: /content/dam/rep:policy
      - filter: /home/users/system/wcm-io-samples/wcmioDamSystemUser

# Application package
- url: mvn:io.wcm.samples/io.wcm.samples.complete//zip
  dir: packages

# Application sample content package
- url: mvn:io.wcm.samples/io.wcm.samples.sample-content//zip
  dir: packages
  condition: ${app.sampleContent}


# Defines configuration parameters and default values
config:
  contentPackage:
    group: wcm-io-samples
    version: ${version}

  app:
    sampleContent: false

  # Log levels
  log:
    projectSpecificLogLevel: warn
