# Define application-specific AEM packages downloaded from Maven Repository.

files:

# Application package
- url: mvn:io.wcm.samples/io.wcm.samples.complete//zip
  dir: packages

# Application sample content package
- url: mvn:io.wcm.samples/io.wcm.samples.sample-content//zip
  dir: packages
  condition: ${sampleContent}


# Defines configuration parameters and default values
config:
  sampleContent: false
